#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ticket: https://github.com/nadav-galili/idan-hermes/issues/15
# Spec: hermes-brother-runbook.md Phase 0, as AMENDED by the Hermes audit
# (research/hermes-audit branch) and the hosting-reset decision (#10):
#   - Box: Hetzner CX23 (x86, 2 vCPU / 4 GB), Falkenstein or Nuremberg
#   - STT: OFF-BOX — ivrit-ai on RunPod serverless, wired as a Hermes
#     `stt.providers` command provider with env_passthrough
#     (NOT HERMES_LOCAL_STT_COMMAND, NOT on-box faster-whisper)
#   - Separate OS users per instance; browser toolsets OFF; 2 GB swap
#
# Values are saved OUTSIDE this (public) repo, in ~/.idan-provision.env.
# Re-running the wizard offers saved values as defaults — safe to Ctrl-C.

ENV_FILE="${IDAN_PROVISION_ENV:-$HOME/.idan-provision.env}"

# code — print a copy-paste command block, indented, without clearing.
code() { printf '%s' "$DIM"; sed 's/^/      /'; printf '%s\n' "$RESET"; }

TOTAL_STAGES=11

banner "Provision the new box — rebuild instance #1 + Phase 0 for Idan's instance #2"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Inventory — what survived the Hostinger cancellation?"
say "Instance #1 (your two profiles) died with the Hostinger VPS. Before buying"
say "anything, establish what you still have. Look for a backup of instance #1's"
say "HERMES_HOME (config.yaml per profile, sessions, memory/state DB) and its"
say "WhatsApp session dir (platforms/whatsapp/session)."
note "No backup ⇒ instance #1 is rebuilt from scratch: reconfigure both profiles"
note "and re-pair every channel (new QR scans). Budget extra time for that."
if confirm "Do you have a usable backup of instance #1's HERMES_HOME?"; then
  ask INSTANCE1_RESTORE_PATH "Path to the backup (local dir/tarball):"
  write_env INSTANCE1_MODE "restore"
  write_env INSTANCE1_RESTORE_PATH "$INSTANCE1_RESTORE_PATH"
else
  write_env INSTANCE1_MODE "scratch"
  warn "Scratch rebuild: have the model/provider keys and channel logins for both profiles at hand."
fi
say ""
step "Also confirm the dedicated physical SIM for Idan's assistant is active and"
step "in a phone you can scan QR codes with (needed in stage 10)."
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Buy the Hetzner CX23"
say "Create the server in Hetzner Cloud Console. You do the purchase — this"
say "wizard never touches payment."
open_url "https://console.hetzner.com/"
step "Create (or pick) a project, e.g. 'idan-hermes'."
step "Add Server → Location: Falkenstein or Nuremberg."
step "Image: Ubuntu 24.04. Type: Shared vCPU x86 → CX23 (2 vCPU / 4 GB / 40 GB)."
step "Networking: keep a PRIMARY IPv4 enabled (~€0.60/mo) — WhatsApp needs clean IPv4."
step "SSH key: add your public key (~/.ssh/id_ed25519.pub) so root login works keyless."
step "Name it (e.g. 'hermes-box') and create. ~€6.1/mo net + VAT, hourly billed."
ask BOX_IP "Paste the server's public IPv4:"
write_env BOX_IP "$BOX_IP"
say ""
step "Verify SSH works before continuing:"
code <<'EOF'
ssh root@<BOX_IP> 'echo ok'
EOF
pause "Did 'ok' print?"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Base box setup — users, swap, packages, SSH hardening"
say "Run this as root on the box (paste the whole block):"
code <<'EOF'
apt-get update && apt-get -y upgrade
apt-get -y install git curl jq ffmpeg build-essential python3-venv
# Node 20 (Baileys bridge needs Node 18+)
curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get -y install nodejs
# 2 GB swap — audit amendment 7 (4 GB RAM fits both instances only with headroom)
fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
echo '/swapfile none swap sw 0 0' >> /etc/fstab
# one OS user per instance — data-level isolation
adduser --disabled-password --gecos "" nadav
adduser --disabled-password --gecos "" idan
loginctl enable-linger nadav && loginctl enable-linger idan
mkdir -p /home/nadav/.ssh /home/idan/.ssh
cp /root/.ssh/authorized_keys /home/nadav/.ssh/ && cp /root/.ssh/authorized_keys /home/idan/.ssh/
chown -R nadav:nadav /home/nadav/.ssh && chown -R idan:idan /home/idan/.ssh
chmod 700 /home/nadav/.ssh /home/idan/.ssh
# SSH hardening: keys only
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl restart ssh
EOF
note "linger lets each user's systemd *user* services run without a login session."
pause "Block ran clean?"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Rebuild instance #1 (your two profiles)"
say "As the 'nadav' user on the box (ssh nadav@$BOX_IP), install Hermes and bring"
say "your two profiles back. Follow the current install doc — don't trust memory:"
open_url "https://hermes-agent.nousresearch.com/docs/getting-started/installation"
step "Install Hermes under the 'nadav' user."
say ""
say "Then, depending on stage 1:"
step "RESTORE: copy the backed-up HERMES_HOME(s) into place (scp from your Mac),"
step "  fix ownership (chown -R nadav:nadav), start the per-profile services."
step "SCRATCH: 'hermes profile create <name>' per profile, re-enter provider keys,"
step "  re-pair each channel (fresh QR scans / logins), restore personas from notes."
step "Either way: per-profile systemd user services with Restart=always."
warn "Instance #1 must NOT share HERMES_HOME, ports, or OS user with instance #2."
pause "Both profiles of instance #1 online and answering?"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Create the PRIVATE brain repo (idan-brain)"
say "The brain lives in a separate PRIVATE repo — never in idan-hermes (public)."
if confirm "Create github.com/nadav-galili/idan-brain (private, empty) via gh now?"; then
  if gh repo create nadav-galili/idan-brain --private >/dev/null 2>&1; then
    printf '  %s✓ created%s nadav-galili/idan-brain (private)\n' "$GREEN" "$RESET"
  else
    warn "gh create failed (already exists, or gh not authed) — create it in the browser."
    open_url "https://github.com/new"
    pause "Private repo 'idan-brain' exists?"
  fi
else
  open_url "https://github.com/new"
  step "Owner nadav-galili, name 'idan-brain', PRIVATE, no README."
  pause "Created?"
fi
step "Double-check the repo shows the 'Private' badge before moving on."
write_env BRAIN_REPO "nadav-galili/idan-brain"
pause

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Deploy key + on-box git (runbook Phase 0, step 2)"
say "As the 'idan' user on the box, set DATADIR (e.g. /home/idan/brain) and run:"
code <<'EOF'
DATADIR=/home/idan/brain
mkdir -p "$DATADIR/.ssh"
ssh-keygen -t ed25519 -N "" -f "$DATADIR/.ssh/idan_brain_deploy" -C idan-brain-deploy
chmod 600 "$DATADIR/.ssh/idan_brain_deploy"
cat "$DATADIR/.ssh/idan_brain_deploy.pub"
EOF
step "Copy the printed .pub line, then add it as a Deploy Key WITH WRITE ACCESS:"
open_url "https://github.com/nadav-galili/idan-brain/settings/keys"
pause "Deploy key added with 'Allow write access' checked?"
say "Back on the box (still as idan) — SSH alias, repo skeleton, first push:"
code <<'EOF'
cat >> "$DATADIR/.ssh/config" <<CFG
Host github-idan-brain
  HostName github.com
  User git
  IdentityFile $DATADIR/.ssh/idan_brain_deploy
  IdentitiesOnly yes
CFG
cd "$DATADIR"
git init
git config user.name "idan-brain-box"
git config user.email "idan-brain@box"
git config core.sshCommand "ssh -F $DATADIR/.ssh/config"
mkdir -p raw notes/{people,decisions,preferences,facts,routines} media
touch raw/.gitkeep media/.gitkeep notes/{people,decisions,preferences,facts,routines}/.gitkeep
printf '# MEMORY\n' > MEMORY.md
printf '# idan-brain\nraw/ is truth; notes/ is a derived, regenerable layer.\n' > README.md
git add -A && git commit -m "skeleton: two-tier brain repo"
git remote add origin git@github-idan-brain:nadav-galili/idan-brain.git
git branch -M main && git push -u origin main
EOF
pause "Push succeeded? (this is half the Phase 0 gate)"

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Provision Hermes instance #2 (Idan's)"
say "As the 'idan' user: install Hermes, create Idan's profile, run it as a"
say "systemd user service with Restart=always — own HERMES_HOME, own port."
open_url "https://hermes-agent.nousresearch.com/docs/user-guide/multi-profile-gateways"
step "Install Hermes under 'idan'; 'hermes profile create idan' (or equivalent)."
step "In its config.yaml: do NOT use the hermes-whatsapp platform preset — it"
step "  bundles terminal/file. List toolsets explicitly; keep BROWSER OFF (RAM)."
step "  Full allowlist lockdown lands in Phase 3; for now just avoid the preset."
step "Service: hermes-gateway-idan.service (user unit), Restart=always."
warn "Never point this instance at the public idan-hermes repo, and never commit"
warn "platforms/whatsapp/session anywhere."
pause "Instance #2 process up (no channel linked yet)?"

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "OpenRouter — prepaid key for instance #2"
say "One prepaid OpenRouter key powers conversation + curation (#12): prepaid"
say "ceiling ~\$10–20/mo IS the cost cap — no subscription, no auto-topup."
open_url "https://openrouter.ai/settings/keys"
step "You buy the credits yourself (\$10–20). Then create an API key named 'idan-box'."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter API key:"
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
step "In instance #2's config.yaml set the main model via OpenRouter — the #12"
step "  decision: conversation = Claude Haiku 4.5 (anthropic/claude-haiku-4.5)."
step "Put the key in the instance's env (systemd unit Environment= or env file"
step "  readable only by 'idan'), then restart the service."
pause "Instance #2 answers a CLI/test message via OpenRouter?"

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Hebrew STT — ivrit-ai on RunPod serverless (off-box, audit amendment 1)"
say "Deploy ivrit-ai's official serverless worker on RunPod (~\$0.03/audio-hr,"
say "scales to zero), then wire it into Hermes as a COMMAND STT PROVIDER."
open_url "https://github.com/ivrit-ai/runpod-serverless"
step "Read the README's deploy section (UI changes; trust it over this wizard),"
step "  then deploy the worker from the RunPod Hub / console:"
open_url "https://console.runpod.io/hub"
step "You create the RunPod account and add prepaid credits yourself (\$5 lasts months)."
step "Deploy the ivrit-ai endpoint (16 GB GPU worker, min workers 0)."
ask RUNPOD_ENDPOINT_ID "Paste the serverless ENDPOINT ID:"
write_env RUNPOD_ENDPOINT_ID "$RUNPOD_ENDPOINT_ID"
step "Settings → API Keys → create a key restricted to this endpoint if possible."
ask_secret RUNPOD_API_KEY "Paste the RunPod API key:"
write_env RUNPOD_API_KEY "$RUNPOD_API_KEY"
say ""
say "On the box, as root, install the wrapper /opt/idan/bin/ivrit-stt.sh:"
code <<'EOF'
mkdir -p /opt/idan/bin && cat > /opt/idan/bin/ivrit-stt.sh <<'WRAP'
#!/usr/bin/env bash
# ivrit-stt.sh <input_audio> <output_txt> <language>
# POSTs audio to the ivrit-ai RunPod serverless endpoint; writes transcript.
# VERIFY the payload shape against github.com/ivrit-ai/runpod-serverless README
# before first use — this is the documented shape as of 2026-08.
set -euo pipefail
in="$1"; out="$2"; lang="${3:-he}"
b64=$(base64 -w0 "$in")
resp=$(curl -sf -X POST \
  "https://api.runpod.ai/v2/${RUNPOD_ENDPOINT_ID}/runsync" \
  -H "Authorization: Bearer ${RUNPOD_API_KEY}" \
  -H "Content-Type: application/json" \
  -d "{\"input\":{\"type\":\"blob\",\"data\":\"${b64}\",\"language\":\"${lang}\"}}")
text=$(printf '%s' "$resp" | jq -r '[.output[]?.text // empty] | join(" ")')
[ -n "$text" ] || { echo "empty transcript: $resp" >&2; exit 1; }
printf '%s' "$text" > "$out"
WRAP
chmod 755 /opt/idan/bin/ivrit-stt.sh
EOF
say "Then in instance #2's config.yaml (NOT the old HERMES_LOCAL_STT_COMMAND):"
code <<'EOF'
stt:
  enabled: true
  provider: ivrit-runpod
  providers:
    ivrit-runpod:
      type: command
      command: "/opt/idan/bin/ivrit-stt.sh {input_path} {output_path} {language}"
      language: "he"
      format: txt
      timeout: 120
      env_passthrough: [RUNPOD_API_KEY, RUNPOD_ENDPOINT_ID]
EOF
note "env_passthrough is required — Hermes scrubs the child env; inherited keys never arrive."
step "Add RUNPOD_API_KEY + RUNPOD_ENDPOINT_ID to the instance's env; restart it."
step "Smoke-test on the box: /opt/idan/bin/ivrit-stt.sh test.ogg /tmp/t.txt he"
pause "Wrapper produced a Hebrew transcript for a test file?"

# ── Stage 10 ──────────────────────────────────────────────────────────────
stage "WhatsApp — QR-link the dedicated SIM + Hebrew persona"
open_url "https://hermes-agent.nousresearch.com/docs/user-guide/messaging/whatsapp"
step "Enable the WhatsApp channel on instance #2; it prints a QR code."
step "On the dedicated-SIM phone: WhatsApp → Linked devices → scan the QR."
step "Set the persona: Hebrew, warm but brief (עברית, חם אבל תמציתי)."
step "Add the assistant to the 1–2 groups Idan wants searchable."
warn "This SIM's WhatsApp is now the assistant. Keep the phone charged until the"
warn "session is stable; session state lives under HERMES_HOME — never in git."
pause "Session linked and stable?"

# ── Stage 11 ──────────────────────────────────────────────────────────────
stage "Phase 0 gate — verify everything"
say "The ticket closes only when ALL of these pass:"
step "1. git push from the box: as 'idan', touch a file in \$DATADIR, commit, push"
step "   → appears on github.com/nadav-galili/idan-brain."
step "2. WhatsApp: message the assistant in Hebrew from your phone → Hebrew reply."
step "3. Voice: send a Hebrew voice note → assistant demonstrably has the Hebrew"
step "   transcript (reply references what you said)."
step "4. Instance #1: both your profiles still answering, untouched by all of the above."
if confirm "All four checks pass?"; then
  printf '  %s✓ Phase 0 gate PASSED%s\n' "$GREEN" "$RESET"
  say "Comment on the ticket with the gate evidence and close it:"
  code <<'EOF'
gh issue close 15 --repo nadav-galili/idan-hermes \
  --comment "Phase 0 gate passed: box up (Hetzner CX23), instance #1 rebuilt, instance #2 provisioned (deploy-key push OK, Hebrew WhatsApp reply OK, RunPod ivrit-ai voice transcript OK, instance #1 unaffected)."
EOF
else
  SKIPPED+=("Phase 0 gate — re-run the wizard (saved values are kept) and fix the failing check")
  warn "Gate not passed — the ticket stays open."
fi

finish
